### PR TITLE
Bounty #28

### PR DESCRIPTION
**Pull request by vhcsilva**
Bounty #28

### CODE REVIEW

**Review by vhcsilva09 — CHANGES_REQUESTED** [review]
review request

**Comment by vhcsilva** [comment]
@vhcsilva said This is the first review on this PR

**Comment by vhcsilva** [comment]
@vhcsilva submitted the review below This is a review with line break

**Comment by vhcsilva** [comment]
@vhcsilva submitted the review below\ This sould have a line break

**Comment by vhcsilva** [comment]
@vhcsilva submitted the review below<br> what about this ?

**Comment by vhcsilva** [comment]
<p>@vhcsilva reviewed this with the following message:</p><p>review comment with p tag</p>

**Comment by vhcsilva** [comment]
<p>@vhcsilva reviewed this with the following message:</p><p>testing reviewers column</p>

**Comment by vhcsilva** [comment]
<p>@vhcsilva09 reviewed this with the following message:</p><p>Reviewing this pull request </p>

**Pull request closed without merging**
